PRAGMA foreign_keys = ON;
CREATE TABLE IF NOT EXISTS schema_migrations(version INTEGER PRIMARY KEY, applied_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS users(id TEXT PRIMARY KEY, email TEXT NOT NULL UNIQUE, name TEXT NOT NULL, role TEXT NOT NULL, password_hash TEXT NOT NULL, created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS sessions(id TEXT PRIMARY KEY, user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE, token_hash TEXT NOT NULL UNIQUE, expires_at TEXT NOT NULL, revoked_at TEXT, created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS students(id TEXT PRIMARY KEY, owner_id TEXT NOT NULL REFERENCES users(id), name TEXT NOT NULL, graduation_year INTEGER NOT NULL, region TEXT NOT NULL, version INTEGER NOT NULL DEFAULT 1, created_at TEXT NOT NULL, updated_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS interests(id TEXT PRIMARY KEY, student_id TEXT NOT NULL REFERENCES students(id) ON DELETE CASCADE, tag TEXT NOT NULL, weight REAL NOT NULL, UNIQUE(student_id, tag));
CREATE TABLE IF NOT EXISTS universities(id TEXT PRIMARY KEY, name TEXT NOT NULL, province TEXT NOT NULL, created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS majors(id TEXT PRIMARY KEY, code TEXT NOT NULL UNIQUE, name TEXT NOT NULL, field TEXT NOT NULL, created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS admission_plans(id TEXT PRIMARY KEY, university_id TEXT NOT NULL REFERENCES universities(id), major_id TEXT NOT NULL REFERENCES majors(id), year INTEGER NOT NULL, quota INTEGER NOT NULL, remaining INTEGER NOT NULL, UNIQUE(university_id, major_id, year));
CREATE TABLE IF NOT EXISTS career_paths(id TEXT PRIMARY KEY, major_id TEXT NOT NULL REFERENCES majors(id), title TEXT NOT NULL, outlook TEXT NOT NULL, UNIQUE(major_id, title));
CREATE TABLE IF NOT EXISTS recommendations(id TEXT PRIMARY KEY, student_id TEXT NOT NULL REFERENCES students(id), created_by TEXT NOT NULL REFERENCES users(id), status TEXT NOT NULL, version INTEGER NOT NULL DEFAULT 1, note TEXT NOT NULL, submitted_at TEXT, approved_at TEXT, created_at TEXT NOT NULL, updated_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS recommendation_items(id TEXT PRIMARY KEY, recommendation_id TEXT NOT NULL REFERENCES recommendations(id) ON DELETE CASCADE, admission_plan_id TEXT NOT NULL REFERENCES admission_plans(id), career_path_id TEXT NOT NULL REFERENCES career_paths(id), priority INTEGER NOT NULL, UNIQUE(recommendation_id, priority));
CREATE TABLE IF NOT EXISTS followups(id TEXT PRIMARY KEY, recommendation_id TEXT NOT NULL REFERENCES recommendations(id), due_at TEXT NOT NULL, status TEXT NOT NULL, attempts INTEGER NOT NULL DEFAULT 0, lease_until TEXT, last_error TEXT, completed_at TEXT, created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS audit_events(id TEXT PRIMARY KEY, actor_id TEXT REFERENCES users(id), entity_type TEXT NOT NULL, entity_id TEXT NOT NULL, action TEXT NOT NULL, result TEXT NOT NULL, request_id TEXT NOT NULL, detail TEXT NOT NULL, created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS idempotency_keys(key TEXT PRIMARY KEY, actor_id TEXT NOT NULL REFERENCES users(id), request_hash TEXT NOT NULL, response_body TEXT NOT NULL, created_at TEXT NOT NULL, expires_at TEXT NOT NULL);
CREATE INDEX IF NOT EXISTS idx_sessions_token ON sessions(token_hash);
CREATE INDEX IF NOT EXISTS idx_plans_lookup ON admission_plans(major_id, year, remaining);
CREATE INDEX IF NOT EXISTS idx_recommendations_student ON recommendations(student_id, status, updated_at);
CREATE INDEX IF NOT EXISTS idx_followups_due ON followups(status, due_at, lease_until);
